# Generated by Django 2.0.1 on 2020-07-03 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.PositiveIntegerField(choices=[(1, '发布'), (0, '删除'), (2, '待发布')], default=1, verbose_name='状态')),
                ('visit', models.SmallIntegerField(default=0, verbose_name='浏览量')),
                ('desc', models.CharField(max_length=256, verbose_name='描述')),
                ('img', models.FileField(default='picture/cover.jpeg', upload_to='picture/%Y/%m/%d/', verbose_name='头像')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='filemanager',
            name='picture',
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-id'], 'verbose_name': '相册', 'verbose_name_plural': '相册'},
        ),
        migrations.AddField(
            model_name='picture',
            name='cover',
            field=models.ImageField(blank=True, upload_to='picture/%Y/%m/%d/', verbose_name='封面'),
        ),
        migrations.DeleteModel(
            name='FileManager',
        ),
        migrations.AddField(
            model_name='imagemanager',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picture.Picture', verbose_name='相册'),
        ),
    ]
