# Generated by Django 2.0.1 on 2020-07-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20200703_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemanager',
            old_name='point',
            new_name='picture',
        ),
    ]
