# Generated by Django 2.0.1 on 2020-07-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20200703_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.PositiveIntegerField(choices=[(1, '发布'), (0, '删除'), (2, '待发布')], default=1, verbose_name='状态')),
                ('visit', models.SmallIntegerField(default=0, verbose_name='浏览量')),
                ('desc', models.CharField(max_length=256, verbose_name='描述')),
                ('img', models.FileField(default='picture/cover.jpeg', upload_to='picture/%Y/%m/%d/', verbose_name='照片')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='imagemanager',
            name='picture',
        ),
        migrations.RenameModel(
            old_name='Picture',
            new_name='Album',
        ),
        migrations.DeleteModel(
            name='ImageManager',
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='picture.Album', verbose_name='相册'),
        ),
    ]
