# Generated by Django 2.0.1 on 2020-07-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20200704_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.FileField(default=1, upload_to='thumbnail/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
