# Generated by Django 2.0.1 on 2020-07-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='No Name', max_length=64, verbose_name='相册名'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='picture/cover.jpeg', upload_to='picture/%Y/%m/%d/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
