# Generated by Django 2.0.1 on 2020-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_auto_20200721_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.CharField(max_length=256, verbose_name='缩略图地址'),
        ),
    ]
