# Generated by Django 2.0.1 on 2020-07-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_auto_20200721_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256, verbose_name='缩略图地址'),
        ),
    ]
