# Generated by Django 2.0.1 on 2020-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_auto_20200723_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='image',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
