# Generated by Django 2.0.1 on 2020-07-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.PositiveIntegerField(choices=[(1, '发布'), (0, '删除'), (2, '待发布')], default=1, verbose_name='状态')),
                ('visit', models.SmallIntegerField(default=0, verbose_name='浏览量')),
                ('name', models.CharField(max_length=32, verbose_name='书名')),
                ('desc', models.CharField(max_length=512, verbose_name='概述')),
                ('cover', models.ImageField(default='cover_book/default.png', height_field=594, upload_to='cover_book/', verbose_name='封面', width_field=420)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.PositiveIntegerField(choices=[(1, '发布'), (0, '删除'), (2, '待发布')], default=1, verbose_name='状态')),
                ('visit', models.SmallIntegerField(default=0, verbose_name='浏览量')),
                ('name', models.CharField(max_length=32, verbose_name='菜名')),
                ('ingredients', models.CharField(max_length=256, verbose_name='食材')),
                ('context', models.CharField(max_length=1024, verbose_name='步骤/心得')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CookingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.PositiveIntegerField(choices=[(1, '发布'), (0, '删除'), (2, '待发布')], default=1, verbose_name='状态')),
                ('name', models.CharField(max_length=32, verbose_name='菜名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.PositiveIntegerField(choices=[(1, '发布'), (0, '删除'), (2, '待发布')], default=1, verbose_name='状态')),
                ('visit', models.SmallIntegerField(default=0, verbose_name='浏览量')),
                ('title', models.CharField(max_length=32, verbose_name='篇名')),
                ('context', models.CharField(max_length=1024, verbose_name='正文')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='life.Book', verbose_name='书籍')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.PositiveIntegerField(choices=[(1, '发布'), (0, '删除'), (2, '待发布')], default=1, verbose_name='状态')),
                ('visit', models.SmallIntegerField(default=0, verbose_name='浏览量')),
                ('context', models.CharField(max_length=1024, verbose_name='感悟')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cooking',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='life.CookingTag', verbose_name='标签'),
        ),
    ]
