# Generated by Django 2.0.1 on 2020-07-13 02:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('init_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
