# Generated by Django 2.0.1 on 2020-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200723_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='article',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
