# Generated by Django 2.0.1 on 2020-07-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cover',
            field=models.ImageField(blank=True, upload_to='travel/%Y/%m/%d/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='imagemanager',
            name='img',
            field=models.FileField(default='travel/cover.jpeg', upload_to='travel/%Y/%m/%d/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='province',
            name='cover',
            field=models.FileField(default='travel/cover.jpeg', upload_to='travel/%Y/%m/%d/', verbose_name='封面'),
        ),
    ]
