# Generated by Django 2.0.1 on 2020-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20200703_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemanager',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
