# Generated by Django 2.0.1 on 2020-07-23 19:21

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='context',
            field=mdeditor.fields.MDTextField(help_text='推荐MarkDown哦！', max_length=512, verbose_name='评论'),
        ),
    ]
